-- ── Migration 031: remove the open workspace_invites read policy ────────────
--
-- Found during the follow-up SELECT-policy sweep of the ruthless review
-- (migration 030 covered writes; this is the same treatment for reads).
-- Empirically proven, not inferred: a completely unrelated authenticated
-- user — no membership in either workspace involved — could run
-- `SELECT * FROM workspace_invites` with no filter and get back every
-- pending invite platform-wide: invited email, role being granted, and
-- the raw 32-byte acceptance token.
--
-- Severity note, not overstated: /api/invite/accept (checked directly)
-- already requires the accepting user's own account email to match
-- invite.email before it lets anyone join, which blocks the most severe
-- outcome — a stranger can't just take a leaked token and join as
-- themselves. What remains is real PII disclosure (who's being hired
-- where, at what access level) to anyone with a free account, plus the
-- residual risk if an attacker happens to control the invited email
-- address itself. Fixing it regardless — the underlying RLS policy was
-- clearly a mistake relative to its own intent, not an accepted tradeoff.
--
-- CONFIRMED SAFE TO DROP: the only real read path for this data,
-- src/app/(app)/invite/[token]/page.tsx, is a server component that uses
-- createSupabaseAdmin() (service_role, bypasses RLS entirely) — it was
-- never depending on this policy in the first place. Grepped every .tsx
-- file in the app for a direct client-side read of workspace_invites:
-- none exists. The existing owners_can_manage_invites policy (ALL command,
-- scoped to is_workspace_owner_or_admin) already covers the one
-- legitimate SELECT use — an owner/admin viewing their own workspace's
-- pending invites in Settings.
--
-- Run AFTER: 030_fix_rls_privilege_escalation.sql

DROP POLICY IF EXISTS anyone_can_read_invite_by_token ON workspace_invites;

-- ── Verification ──────────────────────────────────────────────────────────
-- SELECT polname FROM pg_policy WHERE polrelid = 'workspace_invites'::regclass;
-- (should show only owners_can_manage_invites)
